language: java
jdk:
  - openjdk8

branches:
  only:
    - master

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

# CI 실행 완료시 메일로 알람
notifications:
  email:
    recipients:
      - ykyo.jung@gmail.com

before_deploy:
  - zip -r stock-tracing *
  - mkdir -p deploy
  - mv stock-tracing.zip deploy/stock-tracing.zip

deploy:
  - provider: s3
    local-dir: deploy
    access_key_id: $AWS_ACCESS_KEY # Travis repo settings에 설정된 값
    secret_access_key: $AWS_SECRET_KEY # Travis repo settings에 설정된 값
    bucket: stock-tracing-s3
    region: ap-northeast-2
    skip_cleanup: true
    acl: public_read
    wait-until-deployed: true
    on:
      repo: youngkyo/stock-tracing #Github 주소
      branch: master

  - provider: codedeploy
      access_key_id: $AWS_ACCESS_KEY # Travis repo settings에 설정된 값
      secret_access_key: $AWS_SECRET_KEY # Travis repo settings에 설정된 값
      bucket: stock-tracing-s3 # S3 버킷
      key: stock-tracing.zip # 빌드 파일을 압축해서 전달
      bundle_type: zip
      application: stock-tracing. # 웹 콘솔에서 등록한 CodeDeploy 어플리케이션
      deployment_group: stock-tracing.-group # 웹 콘솔에서 등록한 CodeDeploy 배포 그룹
      region: ap-northeast-2
      wait-until-deployed: true
      on:
        repo: youngkyo/stock-tracing
        branch: master