spring:
  profiles:
    active: local # 기본 환경 선택

# local 환경
---
spring:
  profiles: local
  datasource:
    data: classpath:data-h2.sql # 시작할때 실행시킬 script
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true

# 운영 환경
---
spring.profiles: set1
spring.profiles.include: real-db

server:
  port: 8081

---
spring.profiles: set2
spring.profiles.include: real-db

server:
  port: 8082

---
spring:
  profiles: real-db
  datasource:
        url: jdbc:mariadb://stocktraicing.cnd2gon7lwlv.ap-northeast-2.rds.amazonaws.com:3306/stock_tracing_db
        username: youngkyo
        password: wjddudry14
        driver-class-name: org.mariadb.jdbc.Driver